# Generated by Django 4.1.3 on 2023-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAdmins_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProducts_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_availability', models.PositiveIntegerField()),
                ('product_price', models.FloatField()),
                ('product_image', models.CharField(max_length=2000)),
                ('product_rate', models.PositiveSmallIntegerField()),
                ('product_display', models.TextField()),
                ('product_resoloution', models.CharField(max_length=200)),
                ('product_size', models.FloatField()),
                ('product_os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUsers_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_usname', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
