# Generated by Django 4.1.3 on 2023-01-07 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPBE_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopusers_model',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Use +989xxxxxxxxx or 09xxxxxxxxx', regex='^(?:0|98|\\+98|\\+980|0098|098|00980)?(9\\d{9})$')]),
        ),
    ]
